[project]
name = 'Transparent-Education-Fund-Management'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.applicant-verification]
path = 'contracts/applicant-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.fund-disbursement]
path = 'contracts/fund-disbursement.clar'
clarity_version = 2
epoch = 2.5

[contracts.outcome-tracking]
path = 'contracts/outcome-tracking.clar'
clarity_version = 2
epoch = 2.5

[contracts.scholarship-creation]
path = 'contracts/scholarship-creation.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
